// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCui_CV2W8qQrwnRJpb7ZiOeH3GzokPjEs',
    appId: '1:937495941939:web:87b0dc4c1409c724c7e446',
    messagingSenderId: '937495941939',
    projectId: 'easychat-80f33',
    authDomain: 'easychat-80f33.firebaseapp.com',
    storageBucket: 'easychat-80f33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlagQHaOzucsnJ4nIsNRd6pcI-v3Kxbo8',
    appId: '1:937495941939:android:34865f18d215aae4c7e446',
    messagingSenderId: '937495941939',
    projectId: 'easychat-80f33',
    storageBucket: 'easychat-80f33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT_OU6EL-WLs6-MqbZ911gJokzr1wT_pU',
    appId: '1:937495941939:ios:b73ebe3363f2b193c7e446',
    messagingSenderId: '937495941939',
    projectId: 'easychat-80f33',
    storageBucket: 'easychat-80f33.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT_OU6EL-WLs6-MqbZ911gJokzr1wT_pU',
    appId: '1:937495941939:ios:b73ebe3363f2b193c7e446',
    messagingSenderId: '937495941939',
    projectId: 'easychat-80f33',
    storageBucket: 'easychat-80f33.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCui_CV2W8qQrwnRJpb7ZiOeH3GzokPjEs',
    appId: '1:937495941939:web:917afd9312fd93cac7e446',
    messagingSenderId: '937495941939',
    projectId: 'easychat-80f33',
    authDomain: 'easychat-80f33.firebaseapp.com',
    storageBucket: 'easychat-80f33.appspot.com',
  );

}